# Generated by Django 4.2.5 on 2023-10-06 02:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Member', '0002_alter_usercommunity_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercommunity',
            name='is_mentor',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.CreateModel(
            name='RequestMentor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('upadate_date', models.DateField(auto_now_add=True)),
                ('status', models.IntegerField(blank=True, default=0, null=True)),
                ('UserCommunityId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_community', to='Member.usercommunity')),
                ('mentorId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentorid', to='Member.usercommunity')),
            ],
        ),
    ]
