# Generated by Django 4.2.5 on 2023-09-17 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Member', '0002_alter_myuser_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyUser',
        ),
    ]
