# Generated by Django 3.0.7 on 2023-09-18 17:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Community', '0005_communitycerti_communitydoc_communityformer_communityhistory_exambank'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Member', '0004_myuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserHistory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('update_date', models.DateField(auto_now_add=True)),
                ('content', models.CharField(max_length=255)),
                ('community_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Community.Community')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserCommunity',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('score', models.IntegerField()),
                ('joined_date', models.DateField(auto_now_add=True)),
                ('community_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Community.Community')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Member.MyUser')),
            ],
        ),
    ]
