# Generated by Django 4.2.5 on 2023-10-01 16:22

import Community.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Community', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='entrance_test_enable',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='community',
            name='mentor_threshold',
            field=models.IntegerField(default=0, validators=[Community.models.validate_no_negative]),
        ),
        migrations.AddField(
            model_name='community',
            name='upload_permission',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
