# Generated by Django 4.2.5 on 2023-09-21 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Community', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='num_member',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
