# Generated by Django 4.2.5 on 2023-09-14 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Community', '0002_alter_community_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
