# Generated by Django 4.2.5 on 2023-09-21 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Community', '0002_community_num_member'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='community',
            name='num_member',
        ),
        migrations.AddField(
            model_name='community',
            name='num_of_members',
            field=models.IntegerField(default=0),
        ),
    ]
