# Generated by Django 4.2.5 on 2023-09-21 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Community', '0003_remove_community_num_member_community_num_of_members'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='community',
            name='num_of_members',
        ),
        migrations.AddField(
            model_name='community',
            name='count_member',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
