# Generated by Django 4.2.5 on 2023-09-14 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Community', '0003_community_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='created_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
