# Generated by Django 4.2.5 on 2023-09-21 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Community', '0004_remove_community_num_of_members_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='community',
            name='count_member',
        ),
    ]
