# Generated by Django 3.0.7 on 2023-09-18 17:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Community', '0004_alter_community_created_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamBank',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ques_content', models.CharField(max_length=50)),
                ('answer', models.CharField(max_length=50)),
                ('purpose', models.CharField(max_length=50)),
                ('community_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Community.Community')),
            ],
        ),
        migrations.CreateModel(
            name='CommunityHistory',
            fields=[
                ('commu_history_id', models.AutoField(primary_key=True, serialize=False)),
                ('updated_date', models.DateField(auto_now_add=True)),
                ('updated_content', models.CharField(blank=True, max_length=255)),
                ('community_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Community.Community')),
                ('updated_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CommunityFormer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('community_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Community.Community')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CommunityDoc',
            fields=[
                ('document_id', models.AutoField(primary_key=True, serialize=False)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('title', models.CharField(max_length=100)),
                ('path', models.TextField(max_length=255)),
                ('community_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Community.Community')),
                ('created_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CommunityCerti',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('certificate_type_id', models.IntegerField()),
                ('gained_date', models.DateField(auto_now_add=True)),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('community_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Community.Community')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
