# Generated by Django 3.0.7 on 2023-09-24 03:09

import Community.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Community', '0005_remove_community_count_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='entrance_test_enable',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='community',
            name='mentor_threshold',
            field=models.IntegerField(default=0, validators=[Community.models.validate_no_negative]),
        ),
        migrations.AddField(
            model_name='community',
            name='upload_permission',
            field=models.CharField(default='Freely', max_length=20),
        ),
    ]
