# Generated by Django 4.2.5 on 2023-10-03 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Community', '0006_auto_20230924_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='upload_permission',
            field=models.IntegerField(default=1),
        ),
    ]
